src/Akeneo/UserManagement/Bundle/Form/Type/AclAccessLevelSelectorType.php
<?php

namespace Akeneo\UserManagement\Bundle\Form\Type;

use Akeneo\UserManagement\Bundle\Form\Transformer\AccessLevelToBooleanTransformer;
use Oro\Bundle\SecurityBundle\Acl\AccessLevel;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * AclAccessLevelSelector form type
 *
 * @author    Filips Alpe <filips@akeneo.com>
 * @copyright 2014 Akeneo SAS (http://www.akeneo.com)
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
class AclAccessLevelSelectorType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->addViewTransformer(
            new AccessLevelToBooleanTransformer(),
            true
        );
    }

    /**
     * {@inheritdoc}
     */
    public function getParent(): ?string
    {
        return CheckboxType::class;
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix(): string
    {
        return 'pim_acl_access_level_selector';
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $choices = [
            AccessLevel::NONE_LEVEL,
            AccessLevel::SYSTEM_LEVEL
        ];

        $resolver->setDefaults(
            [
                'choices' => array_combine($choices, $choices)
            ]
        );
    }
}

src/Akeneo/UserManagement/Bundle/Form/Type/ResetType.php
<?php

namespace Akeneo\UserManagement\Bundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Length;

class ResetType extends AbstractType
{
    private const PASSWORD_MINIMUM_LENGTH = 8;
    private const PASSWORD_MAXIMUM_LENGTH = 4096;

    /**
     * @var string
     */
    protected $class;

    /**
     * @param string $class User entity class
     */
    public function __construct($class)
    {
        $this->class = $class;
    }

    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add(
            'plainPassword',
            RepeatedType::class,
            [
                'type'           => PasswordType::class,
                'required'       => true,
                'first_options'  => ['label' => 'Password'],
                'second_options' => ['label' => 'Again'],
                'constraints'    => [
                    new Length([
                        'min' => self::PASSWORD_MINIMUM_LENGTH,
                        'max' => self::PASSWORD_MAXIMUM_LENGTH
                    ])
                ],
            ]
        );
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
            [
                'data_class' => $this->class,
                'intention'  => 'reset',
            ]
        );
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix(): string
    {
        return 'pim_user_reset';
    }
}

src/Akeneo/UserManagement/Bundle/Controller/ResetController.php
<?php

namespace Akeneo\UserManagement\Bundle\Controller;

use Akeneo\UserManagement\Bundle\Form\Handler\ResetHandler;
use Akeneo\UserManagement\Bundle\Manager\UserManager;
use Akeneo\UserManagement\Bundle\Notification\MailResetNotifier;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;

class ResetController extends AbstractController
{
    public function __construct(
        private readonly UserManager $userManager,
        private readonly SessionInterface $session,
        private readonly ResetHandler $resetHandler,
        private readonly TokenStorageInterface $tokenStorage,
        private readonly FormInterface $form,
        private readonly MailResetNotifier $mailer,
    ) {
    }

    public function request(): Response
    {
        return $this->render('@PimUser/Reset/request.html.twig');
    }

    /**
     * Request reset user password
     */
    public function sendEmail(Request $request): Response
    {
        $username = $request->request->get('username');
        $user = $this->userManager->findUserByUsernameOrEmail($username);

        if (null === $user || false === $user->isEnabled()) {
            return $this->render('@PimUser/Reset/sendEmail.html.twig');
        }

        if ($user->isPasswordRequestNonExpired($this->container->getParameter('pim_user.reset.ttl'))) {
            $this->addFlash(
                'warn',
                'The password for this user has already been requested within the last 24 hours.'
            );

            return $this->redirectToRoute('pim_user_reset_request');
        }

        if (null === $user->getConfirmationToken()) {
            $user->setConfirmationToken($user->generateToken());
        }

        $user->setPasswordRequestedAt(new \DateTime('now', new \DateTimeZone('UTC')));
        $this->userManager->updateUser($user);

        $this->mailer->notify($user);

        return $this->render('@PimUser/Reset/sendEmail.html.twig');
    }

    /**
     * Reset user password
     */
    public function reset(string $token): Response
    {
        $user = $this->userManager->findUserByConfirmationToken($token);

        if (null === $user || false === $user->isEnabled()) {
            throw $this->createNotFoundException(
                sprintf('The user with "confirmation token" does not exist for value "%s"', $token)
            );
        }

        if (!$user->isPasswordRequestNonExpired($this->container->getParameter('pim_user.reset.ttl'))) {
            $this->addFlash(
                'warn',
                'The password for this user has already been requested within the last 24 hours.'
            );

            return $this->redirectToRoute('pim_user_reset_request');
        }

        if ($this->resetHandler->process($user)) {
            $this->addFlash('success', 'Your password has been successfully reset. You may login now.');

            // force user logout
            $this->session->invalidate();
            $this->tokenStorage->setToken(null);

            return $this->redirectToRoute('pim_user_security_login');
        }

        return $this->render('@PimUser/Reset/reset.html.twig', [
            'token' => $token,
            'form' => $this->form->createView(),
        ]);
    }
}

src/Akeneo/UserManagement/Bundle/Resources/views/Reset/_fields.html.twig
{% extends '@PimUI/Form/pim-fields.html.twig' %}

{% block form_row_field %}
    <div class="InputBlock{% if attr.class is defined %} {{ attr.class }}{% endif %}">
        {{ form_label(form, '', { label_attr: label_attr|merge({ class: 'InputLabel' })}) }}
        <div class="InputContainer">
            {{- form_widget(form) -}}
        </div>
        {{- form_errors(form) -}}
    </div>
{% endblock %}

{%- block form_widget_simple -%}
    {%- set type = type|default('text') -%}
    {% set class = attr.class ?? '' %}
    {% if type == 'text' or type == 'password'  %}
        {% set class = 'InputText' %}
    {% endif %}
    {% if errors|length > 0  %}
        {% set class = class ~ ' ' ~ 'error' %}
    {% endif %}
    {% set attr = attr|merge({'class': class }) %}
    <input type="{{ type }}" {{ block('widget_attributes') }} {% if value == '\\' or value is not empty %}value="{{ value }}" {% endif %}/>
{%- endblock form_widget_simple -%}

{% block form_label %}
    {% apply spaceless %}
        {% if label is not same as(false) %}
            {% set label_attr = label_attr|merge({'class': (label_attr.class|default('') ~ ' AknFieldContainer-label')|trim}) %}
            {% if not compound %}
                {% set label_attr = label_attr|merge({'for': id}) %}
            {% endif %}
            {% if required %}
                {% set label_attr = label_attr|merge({'class': (label_attr.class ~ ' required')|trim}) %}
            {% endif %}
            {% if label is empty %}
                {% set label = name|humanize %}
            {% endif %}
            {% set isRadioLabel = form.parent.vars.expanded|default(false) and checked is defined %}
            {% set label = label|trans({}, translation_domain) %}
            {% if label_attr.truncate is defined and label_attr.truncate %}
                {% set label_attr = { 'title': label }|merge(label_attr) %}
                {% set label_attr = label_attr|merge({ 'class': (label_attr.class is defined ? label_attr.class ~ ' ' : '') ~ 'truncate' }) %}
            {% endif %}
            <label {% for attrname, attrvalue in label_attr | filter(attrname => attrname != 'truncate') %} {{ attrname }}="{{ attrvalue }}"{% endfor %}>
            {% if form.parent.vars.mode is defined and 'comparison' == form.parent.vars.mode %}
                <input type="checkbox" class="comparisonSelection exclude" />
            {% else %}
                {{ label }}{% if required and not isRadioLabel %} {{ 'required'|trans }}{% endif %}
            {% endif %}
            </label>
        {% endif %}
    {% endapply %}
{% endblock form_label %}

{%- block form_errors -%}
    {%- if errors|length > 0 -%}
        {%- for error in errors -%}
            <div class="Helper {% if form.parent %}Helper--inline{% endif %}">
                <span class="Icon"></span>
                <span class="Text">{{ error.message }}</span>
            </div>
        {%- endfor -%}
    {%- endif -%}
{%- endblock form_errors -%}

src/Akeneo/UserManagement/Bundle/Resources/views/Reset/request.html.twig
{% extends '@PimUser/layout.html.twig' %}

{% block bodyClass %}AknLogin{% endblock %}

{% block content %}
    <form action="{{ path('pim_user_reset_send_email') }}" method="post" class="Form">
        <div class="InputGroup">
            <div class="InputBlock">
                <label class="InputLabel" for="username">{{ 'pim_user.user.login.username_or_email'|trans }}</label>
                <input class="InputText" type="text" id="username" name="username" required="required" autofocus="autofocus"/>
            </div>
            <div class="CancelPasswordReset">
                <a href="{{ path('pim_user_security_login') }}" class="AknLogin-link cancel">{{ 'pim_common.cancel'|trans }}</a>
            </div>
        </div>
        <button type="submit" class="AknButton AknButton--apply" id="_submit">
            {{- 'pim_user.user.login.request'|trans -}}
        </button>
    </form>
{% endblock %}

{% block deferred_javascript %}
    {{ parent() }}
    <script type="text/javascript" nonce="{{ js_nonce() }}">
      (function () {
        const username = document.getElementById('username');
        const submit = document.getElementById('_submit');
        const form = document.querySelector('form.Form');

        initPimLoginForm([username], submit, form);
      })();
    </script>
{% endblock %}

src/Akeneo/UserManagement/Bundle/Resources/views/Reset/reset.html.twig
{% extends '@PimUser/layout.html.twig' %}

{% form_theme form '@PimUser/Reset/_fields.html.twig' %}

{% block bodyClass %}AknLogin{% endblock %}

{% block messages %}
    {{ form_errors(form) }}
{% endblock %}

{% block content %}
    {{ form_start(form, {
        'action': path('pim_user_reset_reset', {token: token}),
        'method': 'post',
        'class': 'Form'
    }) }}
    <div class="InputGroup">
        {{ form_widget(form.plainPassword, {'required': true}) }}
        <div class="CancelPasswordReset">
            <a href="{{ path('pim_user_security_login') }}">{{ 'pim_common.cancel'|trans }}</a>
        </div>
    </div>
    <button type="submit" id="_submit" class="AknButton AknButton--apply">
        {{- 'pim_user.user.login.reset'|trans -}}
    </button>
    {{ form_end(form) }}
{% endblock %}

{% block deferred_javascript %}
    {{ parent() }}
    <script type="text/javascript" nonce="{{ js_nonce() }}">
      (function () {
        const passwordFirst = document.getElementById('pim_user_reset_form_plainPassword_first');
        const passwordSecond = document.getElementById('pim_user_reset_form_plainPassword_second');
        const submit = document.getElementById('_submit');
        const form = document.querySelector('form.Form');

        initPimLoginForm([passwordFirst, passwordSecond], submit, form);
      })();
    </script>
{% endblock %}

src/Akeneo/UserManagement/Bundle/Resources/views/Reset/sendEmail.html.twig
{% extends '@PimUser/layout.html.twig' %}

{% block bodyClass %}AknLogin{% endblock %}

{% block messages %}
    <div class="Helper Helper--info">
        <span class="Icon"></span>
        <span class="Text">{{ 'pim_user.user.login.password_reset_email_sent'|trans }}</span>
    </div>
{% endblock %}

{% block content %}
    <div class="Form">
        <div class="InputGroup">
            <div class="CancelPasswordReset">
                <a href="{{ path('oro_default') }}">{{ 'pim_user.user.login.homepage'|trans }}</a>
            </div>
        </div>
    </div>
{% endblock %}